### ISSUE TITLE
DBG2OLC': free(): invalid pointer

### ISSUE THREAD

**Issue by CeciliaDeng** [yechengxi/DBG2OLC#10]
@yechengxi 
This command:

`DBG2OLC k 17 AdaptiveTh 0.001 KmerCovTh 2 MinOverlap 15 RemoveChimera 1 Contigs contigs.fasta f PacBio_CorrectTrimmed_30x.fasta`

failed with exceptions:

> **\* Error in `/software/bioinformatics/DBG2OLC/DBG2OLC': free(): invalid pointer: 0x0000000022ddec42 ***
> ======= Backtrace: =========
> /lib64/libc.so.6(+0x7d053)[0x2b508ba0d053]
> /software/DBG2OLC/DBG2OLC[0x40db64]
> /software/DBG2OLC/DBG2OLC[0x403d52]
> /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b508b9b1b15]
> /software/DBG2OLC/DBG2OLC[0x408d91]
> ======= Memory map: ========
> 00400000-00455000 r-xp 00000000 00:25 4726198077                         /software/DBG2OLC/DBG2OLC
> 00655000-00656000 r--p 00055000 00:25 4726198077                         /software/DBG2OLC/DBG2OLC
> 00656000-00657000 rw-p 00056000 00:25 4726198077                         /software/DBG2OLC/DBG2OLC
> 01371000-19a4c3000 rw-p 00000000 00:00 0                                 [heap]
> 2b508af4c000-2b508af6d000 r-xp 00000000 fd:00 396321                     /usr/lib64/ld-2.17.so
> 2b508af6d000-2b508af6f000 rw-p 00000000 00:00 0
> ......
> ....
> 7ffc1d5e4000-7ffc1d606000 rw-p 00000000 00:00 0                          [stack]
> 7ffc1d67e000-7ffc1d680000 r-xp 00000000 00:00 0                          [vdso]
> ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
> /home/user1/.lsbatch/1477646807.85583: line 8: 11668 Aborted                 (core dumped)

Is this caused by not enough RAM? How to get it fixed? Any suggestion is very much appreciated.

**Comment by yechengxi** [comment]
It could be due to incompatible data format. Have you tried to prepare the data as in the manual?

**Comment by CeciliaDeng** [comment]
@yechengxi yes, I followed the Step 0 in the manual to generate _**PacBio_CorrectTrimmed_30x.fasta**_

**Step 0.1**: Prepare PacBio data from error-corrected, trimmed PacBio reads. This step completed succesfully
`/DBG2OLC/compiled/SelectLongestReads sum 18000000000 longest 1 o PacBio_CorrectTrimmed_30x.fasta f SampleID.trimmedReads.fasta.gz`

**Step 0.2**: Prepare Illumina data. 
`/DBG2OLC/compiled/SelectLongestReads sum 24000000000 longest 0 o Illumina_PE_40x.fasta f PE_1.fastq.gz f PE_2.fastq.gz`

Although the Illumina reads are all with the same length (100bp), this step **FAILED** with

> terminate called after throwing an instance of 'std::length_error'
>   what():  basic_string::resize
> ~/.lsbatch/1476834650.83211: line 8: 28505 Aborted                 (core dumped)

**Step 1**. De novo assembly of Illumina data (with ALLPATHS-lg). The contigs.fasta file was created

**Step 2**. Run DBG2OLC using input created in Step 1 and Step 0.1
`/DBG2OLC/DBG2OLC k 17 AdaptiveTh 0.001 KmerCovTh 2 MinOverlap 15 RemoveChimera 1 Contigs $contigs f PacBio_CorrectTrimmed_30x.fasta`

This failed with exceptions that I reported in my first post

> **\* Error in `/software/bioinformatics/DBG2OLC/DBG2OLC': free(): invalid pointer: 0x0000000022ddec42 ***

Can you spot anything wrong in the above steps? How can we fix the error and move on? Thank you.

**Comment by yechengxi** [comment]
NOte that in step 0.2 you need to unzip the gz files first.
