### ISSUE TITLE
split_and_run_sparc has typos

### ISSUE THREAD

**Issue by biorover** [yechengxi/DBG2OLC#15]
blasr command in split_and_run_sparc gives flags with one hyphen, blasr currently only excepts commands with double hyphens (e.g. '-nproc' should be '--nproc').

**Comment by yechengxi** [comment]
At the time of our development blasr was accepting single hyphen. Is it new in some latest versions?

https://github.com/PacificBiosciences/blasr/blob/master/README.MANUAL.md

**Comment by biorover** [comment]
The blasr version I downloaded (5.3.8d086d7), as compiled on my ubuntu 12.04.5 with gcc (5.4.1 I think), did not accept single hyphens. It returns e.g. "ERROR: -nproc is not a valid option", but works fine when options are given with double hyphens. Not sure if it's a blasr version thing or an operating system thing.
