### ISSUE TITLE
Problem with step III

### ISSUE THREAD

**Issue by ulaszewski** [yechengxi/DBG2OLC#16]
Hi, 
I have used contigs from platanus to make the step II and fasta pacbio reads. Now I'm stuck at step III do you have any advice?

./split_and_run_sparc.sh: 27: ./split_and_run_sparc.sh: cmd+=blasr -nproc 64 ./consensus_dir/backbone-1358.reads.fasta ./consensus_dir/backbone-1358.fasta -bestn 1 -m 5 -minMatch 19 -out ./consensus_dir/backbone-1358.mapped.m5; : not found

**Comment by yechengxi** [comment]
This should be a simple issue. But I am not sure what is not found here. If you are familiar with Linux scripts you should be able to trace the problem. It could be that the script was interrupted or blasr wasn't properly called.

**Comment by ulaszewski** [comment]
@yechengxi I had a major problems to install blasr so I had to use a compiled version. But I did not notice the  _cmd=""_ in the script, after removing it and replacing the call for blasr with _./blasr_ step III  runned perfectly. Thanks for the tip.

**Comment by yechengxi** [comment]
Glad to here that. I had the same experience with installing blasr.
