### ISSUE TITLE
raw pacbio

### ISSUE THREAD

**Issue by tangerzhang** [yechengxi/DBG2OLC#17]
Just want to make sure that DBG2OLC take raw pacbio reads for the hybrid assembly, rather than corrected pacbio reads, right?
Thanks!

**Comment by yechengxi** [comment]
correcct.

**Comment by Timothy-WANG** [comment]
So, user needs to correct the read before execute the command ? 
$ ./DBG2OLC k KmerSize AdaptiveTh THRESH_VALUE1 KmerCovTh THRESH_VALUE2 MinOverlap THRESH_VALUE3 Contigs NGS_CONTIG_FILE f **LONG_READS.FASTA** RemoveChimera 1

**Comment by tangerzhang** [comment]
I think Chengxi means that we do not need to correct the pacbio reads.
The program DBG2OLC will solve the problem itself.

**Comment by yechengxi** [comment]
We don't need to correct the pb reads. We correct them with the consensus algorithm in the last step.
