### ISSUE TITLE
Problem in step3-Call consensus

### ISSUE THREAD

**Issue by Timothy-WANG** [yechengxi/DBG2OLC#18]
The first two steps in OK, but in the step3 it come the problems by using 
$ sh split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_reads.fasta ./consensus_dir 2 >cns_log.txt
The error as follow. So, what's wrong with it?
/bin/rm: cannot remove './consensus_dir/backbone-*': No such file or directory
./split_and_run_sparc.sh: 17: ./DBG2OLC/DBG2OLC/utility/split_and_run_sparc.sh: ./split_reads_by_backbone.py: not found
ls: cannot access './consensus_dir/*.reads.fasta': No such file or directory
./split_and_run_sparc.sh: 1: eval: cannot create ./consensus_dir/final_assembly.fasta: Directory nonexistent

**Comment by yechengxi** [comment]
Please give it a try on a small dataset. I think you had problem running the scripts on your environment. You may be able to figure out the issue if you run the scripts line by line.

**Comment by ulaszewski** [comment]
@CHEKNP try to change the mode of ./consensus_dir with e.g. chmod 777 consensus_dir in my case it helped.

**Comment by Timothy-WANG** [comment]
＠ulaszewski　Thanks for your suggestions, however it do not works. While I have noticed in the shell scripts that the STEP3 need some file that come from the parameter of **[OUTPUT_DIR]**, with some files like **${split_dir}/backbone-*** and **${split_dir}/*.reads.fasta** on it, so I am wondering whether the [OUTPUT_DIR] is come from the result of STEP2 ?

**Comment by ulaszewski** [comment]
@CHEKNP 
Here is my second hint, try  chmod **-R** 777 consensus_dir
The -R is critical here.
