### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by npavlovikj** [yechengxi/DBG2OLC#19]
I have been running DBG2OLC on few datasets, and for some of them, when I run "SparseAssembler", 0 contigs are reported and most of the generated files are empty. When I next run "DBG2OLC" I get "80415 Floating point exception" for the DBG2OLC step. I tried running these assemblies with different values and combinations of the parameters, but I still get "Floating point exception" and empty files. I would appreciate if you can tell me how to avoid this error and what combination of parameters I should use to get an output.

**Comment by yechengxi** [comment]
You need to make sure that SparseAssembler runs properly. The Contigs.txt file is the major input to DBG2OLC. If that is not produced properly DBG2OLC cannot be run properly.

**Comment by npavlovikj** [comment]
Thanks @yechengxi for your prompt reply. So, how can I make sure that "SparseAssembler" will return me some results ? I am not getting any errors when I run "SparseAssembler", and I tried different combinations of the parameters' values for "SparseAssembler", but still the contigs file is empty.

**Comment by yechengxi** [comment]
Could you post here the command you used to run it? SparseAssembler should produce correct results if your command and files are correct. It has been tested for many years. Have you tried some standard datasets to verify that you have run it correctly?
