### ISSUE TITLE
full_layout.fasta and graph outputs

### ISSUE THREAD

**Issue by colindaven** [yechengxi/DBG2OLC#2]
Hi,

thanks for a nice and very quick program. It seems to have improved my assembly substantially already.

Two questions:

1- what exactly is this file (full_layout.fasta)? 

Background- the backbone_raw.fasta is only about only 60% of the expected genome size (1.3 of ~2.3 gb), yet the full_layout is 1.8gb. I expect many extra repeats will be present in the full_layout, as this is a repeat rich plant genome with > 70% repeats.

Can I use the full_layout instead of the backbone, or will downstream programs not work ?

2 - what is the best way to view the .dot files. Also which .dot file might be useful ?

I thought the package bandage might be ideal, yet the .dot format output is not supported. Gephi ist struggling with 130000+ nodes...... Bandage supports lastgraph, gfa, trinity fasta .....

https://rrwick.github.io/Bandage/

Thanks!
Colin

**Comment by yechengxi** [comment]
The full_layout.fasta file contains sequences used to build the backbone. Some of them overlap so the resulting backbone file is smaller.

I recommend looking at the CleanedBestOverlapGraph.dot, to visualize the graph I used the dot program in graphviz.

adding
-Ksfdp will make the dot program scale well to extremely large graph

also you might wish to add
-Goverlap=prism to make tags non-overlap so things look well

**Comment by colindaven** [comment]
Hi, thanks for these hints.

I believe I found an error in the consensus part of the docs.

The following command does not run because ctg_reads.fasta cannot be found. I think ctg_pb.fasta as created with the cat command should be used. Correct ?

-file not found
sh ./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_reads.fasta ./consensus_dir 2 >cns_log.txt

-works
sh ./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_pb.fasta ./consensus_dir 2 >cns_log.txt

**Comment by colindaven** [comment]
Another quick question. I expect full_layout.fasta provides a better estimate of the highly repetitive genome given it is far closer to the expected genome size, even if the backbone_raw.fasta is recommended.

Can I use full_layout.fasta in the consensus step ? 

Thanks
Colin

**Comment by yechengxi** [comment]
Hi Colin,
Thank you for pointing out the issue in consensus call. 

However, full_layout.fasta cannot be used for the consensus since it is just a unprocessed collection of sequences. These sequences must be joined to create the backbone file.

**Comment by colindaven** [comment]
Hi,

I may be wrong but there might be another issue in the consensus call

#on site
sh ./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_pb.fasta ./consensus_dir 2 >cns_log.txt

#what I think is intended ("2 >cns_log.txt" -> "2>cns_log.txt"

This is very helpful for debugging, I think I am having issues with the ulimit (which wasn't clear in the output log before)

rm: cannot remove './consensus_dir5/backbone-*': No such file or directory
Traceback (most recent call last):
  File "./split_reads_by_backbone.py", line 131, in <module>
  File "./split_reads_by_backbone.py", line 122, in main
IOError: [Errno 24] Too many open files: './consensus_dir5/backbone-33630.reads.fasta'

Trying to fix and run on a server that I am allowed to restart

**Comment by yechengxi** [comment]
The '2' is the number of consensus iterations, which is a parameter required by the script. You may need to request the privilege to use ulimit otherwise you can also run it on a local machine.
