### ISSUE TITLE
A problem with the number of files (Python)

### ISSUE THREAD

**Issue by andreyurch** [yechengxi/DBG2OLC#20]
Traceback (most recent call last):
  File "/export/home/aay2c/app2/DBG2OLC-master/utility/split_reads_by_backbone.py", line 131, in <module>
  File "/export/home/aay2c/app2/DBG2OLC-master/utility/split_reads_by_backbone.py", line 122, in main
IOError: [Errno 24] Too many open files: './consensus_dir/backbone-2778.reads.fasta'

**Comment by yechengxi** [comment]
We need to open a lot of files to distribute the above file into lots of smaller files so please make sure you have the privilege to run:
ulimit -n unlimited

**Comment by andreyurch** [comment]
Thank you for the answer, but I found that: it is almost impossible to modify this parameter on the Mac OS starting from El Captain.  I and many other potential users of the DBG2OLC do not have the root privileges to modify ulimit on the Linux systems. So, I am completely stacked at this point, while the backbone assembly is perfect...

**Comment by yechengxi** [comment]
I see. Please take a look at other forks of DBG2OLC and see if their correction works. If so, please let me know and I would try to merge them. 

For example:
https://github.com/JohnUrban/DBG2OLC

**Comment by andreyurch** [comment]
Hello, Yes I have finished successfully with https://github.com/JohnUrban/DBG2OLC/tree/split_reads_by_backbone_minimize_open_files/utility

**Comment by yechengxi** [comment]
Cool. Thanks for the feedback!
