### ISSUE TITLE
KeyError from split_reads_by_backbone.py

### ISSUE THREAD

**Issue by dalbada** [yechengxi/DBG2OLC#21]
Hello,

First, thank you very much for this excellent software!

I am trying to perform consensus calling. I run 'split_and_run_sparc.sh', and split_and_run_sparc.sh shows an error message like:

Traceback (most recent call last):
  File "./split_reads_by_backbone.py", line 131, in <module>
    main()
  File "./split_reads_by_backbone.py", line 114, in main
    id = backbone_to_id[backbone]
KeyError: 'seq1435979_len218_cov188'

I have been trying to find what causes this, but I cannot yet.

It must be very grateful if you tell me some idea how to solve my problem.

Kiwoong,

**Comment by yechengxi** [comment]
Sorry I haven't seen this issue before. However, I have updated this part with some scripts contributed by other developers. Please give the new scripts a try.

**Comment by dalbada** [comment]
Thank you for your reply.

Just to understand correctly. In the 'utility' directory, there are several files whose names start with 'split_and_run_'. Could you tell me which file should I use?

**Comment by yechengxi** [comment]
I would use the one that is related with _sparc. There is also a txt file that contains the commands.
