### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ipavanellisouza** [yechengxi/DBG2OLC#27]
Hi! I am trying to perform the Step2 - Overlap and layout - using the contigs generated with Soapdenovo2 (using illumina reads) and pacbio long reads. I keep getting this error message of "Segmentation fault" above:

/var/spool/gridengine/execd/localhost/job_scripts/390: line 4: 13803 Segmentation fault      (core dumped) ./DBG2OLC k 17 AdaptiveTh 0.001 KmerCovTh 2 MinOverlap 10 RemoveChimera 1 Contigs /home/isabela/scaf_DBG2OLC/sugaracane_soap.fasta f /home/isabela/scaf_DBG2OLC/pacbio_ccs_cor10x.fasta

Would you please enlighten me?

Thank you!

**Comment by yechengxi** [comment]
Most likely the result from soap is not compatible with DBG2OLC.

**Comment by ipavanellisouza** [comment]
Thank you for your reply! I'm gonna try with SparseAssembler!
