### ISSUE TITLE
step0 option total length

### ISSUE THREAD

**Issue by nachuwei** [yechengxi/DBG2OLC#28]
Hi,
I'm a beginner with assembly. In the step0 "SelectLongestReads", the option "sum" confuses me.
What's the "total length" meaning? Is it the genome size? or is it sequencing all reads bases?
and
In the manual, "SelectLongestReads" only input Illumina_R1 file. So, in DBG2OLC, is Illumina_R2 file not necessary? 
Thank you so much

**Comment by yechengxi** [comment]
Total length means the total number of bases.
This function selects a number of bases and output to a new file. 
Please play around with small parameters.

**Comment by nachuwei** [comment]
Thank you for your reply!
