### ISSUE TITLE
Short read contig selection for calculation of compressed reads

### ISSUE THREAD

**Issue by slimsuite** [yechengxi/DBG2OLC#29]
For "multi-threaded" assembly of large genomes, [here](https://github.com/yechengxi/DBG2OLC#large-genomes) you say:

> Run DBG2OLC with the same set of parameters _and Illumina Contigs_ in each of these directories...

Forgive a possibly stupid question but does it always need to have the same set of Illumina contigs? In other words, is the calculation of compressed reads dependent on the Illumina contigs?

I ask because it would otherwise be useful to run this step on a bunch of PacBio files and then use the combined compressed set with different Illumina assemblies.

**Comment by yechengxi** [comment]
Yes, the Illumina contigs are the same set of contigs that are generated in the previous step. Using the same set of contigs lead to coherence in compression.
