### ISSUE TITLE
Create_Local_Contig_Kmer_Index(GraphConstruction.h) SegFault

### ISSUE THREAD

**Issue by bredeson** [yechengxi/DBG2OLC#31]
Hey yechengxi,

Thank you for this fast and effective assembly program! I have been assembling a genome with DBG2OLC and encountered an issue while generating contigs. DBG2OLC gets through nearly all local contig kmer indices (writes 1.4 Gb of 1.5 Gb) but encounters two such indices that cause SegFaults.  I have tracked the issue down to line 4497 as an index-out-of-bounds error. It appears that the values for `aligned_contig` and `LongReadContigIndex1.CTG2LR[aligned_contig].size() / 2` are both `0` and trigger this SegFault when attempting to use those values as keys in the `LongReadContigIndex1.CTG2LR` map.

The debugging output for the first problematic index compressed read-read alignment is:
```
result=5
<blank line>
<blank line>
19236 -34074 32495 86089 59772 -19042 -33188 35243 97100 -59673 -89937 65689 -58388 
119758 97100 -59673 -89937 60211 -58388 -34298 93059 -33188
```

For the second problematic index compressed read-read alignment is:
```
result=5
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 69682 69682 69682 67666 69682 67666 69682 67666 69682 67666 69682 67666 67666 69682 67666 69682 
-49100 41853 -49100 67666 -49100 -49100 -49100 -49100 41853 -49100 41853 -49100 -49100 41853 69682 -49100 -49100 -49100 -49100 41853 -49100 -49100 -49100 -491
-6008 -59287 96539 41853 -71445 67667 96538 -6008 -69683 67666 -49100 69682 -71444 
67666 -49100 41853 69682 -49100 -49100 -49100 73346 -49100 73344 -49100 -71515 -49502 10153 -49100 -49502 -49502 73345 -49502 -49502
```

Any help you could provide for fixing/handling this would be appreciated. Thank you!

Best wishes,
bredeson

**Comment by yechengxi** [comment]
Result 5 means the two sequences do not align, however, they were recognized to align in an earlier stage, as you have this bug in the final backbone construction step. 
I wonder if the program is called in an advanced way?

**Comment by bredeson** [comment]
Hey @yechengxi,

I  have ~38x of RSII data with read L50 of 18.8kb, reads 3kb+ only. I ran DBG2OLC with the following parameters:
```
DBG2OLC LD 0 k 17 KmerCovTh 2 MinOverlap 20 AdaptiveTh 0.005 RemoveChimera 1 MinLen 3000 Contigs contigs.fa f subreads.3kb.fasta
```

This produced a segfault. Varying the `AdaptiveTh` parameter also produced segfaults on some (but not all) runs.

**Comment by yechengxi** [comment]
Hi Bredeson,
I see no problem in your command, but may I know which NGS assembler did you use for the Illumina assembly?

**Comment by bredeson** [comment]
Hey @yechengxi,

I used contigs generated by 10X Genomics' Supernova, as they were more complete than contigs I could generate with other assemblers. The organism I'm attempting to assemble is highly inbred, by the way.

**Comment by yechengxi** [comment]
This could be the cause of the seg fault. I have no idea if other assemblers had heuristics that create unexpected structures for DBG2OLC. But you may be able to dig further into the problem as you did in the head of the thread. I would say you are pretty close to a solution.

**Comment by bredeson** [comment]
@yechengxi,
Would it be sufficient to include a conditional statement to check if the result is 5 and `return` from `Create_Local_Contig_Kmer_Index()` to handle this case?  On that note, however, I do see in my log file that other alignments have returned result=5 without segfaulting...

**Comment by yechengxi** [comment]
If I remember correctly (about this 2 yr old project) if the result is 5 we still need to use the alignment to build the backbone.
Result 5 means the alignment is poor. But still, we need to look at the alignment result to join the reads. This means, find a shared contig, find some shared k-mers and join somewhere.
I just wonder what is happening in your environment.
