### ISSUE TITLE
DBG2OLC parameters for huge dataset of PacBio

### ISSUE THREAD

**Issue by uceleste** [yechengxi/DBG2OLC#33]
Hi yechengxi,

I have a plant genome of ~350 Mb (assuming diploid) to assemble. I would try DBG2OLC with ~20x of Illumina (3 dataset) and ~70x of PacBio (1 dataset).
I have a couple of questions:
1) As regards the parameter genome size "GS", the software is expecting the haploid or diploid size of the genome?
2) With such a huge amount of PaBio (~70x), do you suggest some specific values for "AdaptiveTh #", "KmerCovTh #", "MinOverlap #" and "RemoveChimera #"?
3) I'm not sure of understanding the functionality of the parameter "LD 0/1" in the process SparseAssembler. Can you explain it to me please?

Thank you very much for your patience

**Comment by yechengxi** [comment]
GS can be set to a larger size.
The parameters are suggested in the project page. You may refer to the high coverage case.
LD should be set to 0 for the first run. After your first run, LD can be set to 1 to fine tune the parameters.

**Comment by uceleste** [comment]
Perfect, thank you very much for the information!
