### ISSUE TITLE
Any information for  Hardware requirements and expected run times for large genomes hybrid assembly?

### ISSUE THREAD

**Issue by 52teth** [yechengxi/DBG2OLC#36]
Hi chengxi,
Thanks for your excellent work on hybrid assembly of large genomes. Now we are working on the assembly of  larege plant genome(genome size more than 10G) with 30X pacbio and 100x  illumina PE150(insert size 500bp), is it possible to use DBG2OLC to do the hybrid assemble? By the way, is there any  hardware requirements (eg. RAM, cups, disks space)and expected run times for large genome hybrid assemble (eg. genome size 2G, 3G, 6G or 10G and above)?

Thanks a lot for any reply!

**Comment by yechengxi** [comment]
The largest I have done is the human genome. Due to the relative low complexity the assembly was finished in thousands of CPU hours. With this sized genome things can be harder to predict. I would say 200gb memory may be necessary and the parameter tuning can take some time.

**Comment by 52teth** [comment]
I really appreciate your reply! I'll have a try for my dataset.
