### ISSUE TITLE
larger genome size

### ISSUE THREAD

**Issue by hermeseduardo** [yechengxi/DBG2OLC#37]
hi there,

I am getting twice the genome size as backbone_raw.fasta and as final output, could you please indicate what can be happening? and how to correct it? 30X Pacbio and 70X Illumina (250bp and 150bp). 
Bellow an example of the arguments used, but also tried several options with the same results.
DBG2OLC LD1 0 KmerCovTh 2 MinOverlap 20 AdaptiveTh 0.01 RemoveChimera 1 k 17

thanks

**Comment by yechengxi** [comment]
Hello, it is quite rare to have larger assembly than the genome size. Could you go through the test cases to make sure everything is correct?

**Comment by bredeson** [comment]
Hi, have you done any parameter tweaking?  The parameters could be optimized to pull more contigs together and reduce the number of redundant sequence. Alternatively, could the genome be highly heterozygous? The haplotypes could have assembled apart if the species diversity is very high. I have seen this happen for a few genomes I've worked with.

**Comment by hermeseduardo** [comment]
Hi, thanks, sure I did a lot of tweaking, surely there is some heterozygocity but not that high.

 I just tried for one of the test cases, S_cer_w303, and got:

-Contigs.txt N50 = 33457, Total length = 11362747bp

-backbone_raw.fasta, N50 = 37917bp Total length = 4301991bp

I use the whole dataset  from Scer_W303 folder, without sub-sampling:
Pacbio.fasta.gz, Illumina_500bp_2x300_R1_sampled.fastq.gz

The run was as follow:

module load dbg2olc/20160920 python blasr/3.0.1

SparseAssembler LD 0 k 51 g 15 NodeCovTh 1 EdgeCovTh 0 GS 12000000 f
Illumina_500bp_2x300_R1_sampled.fastq

SparseAssembler LD 1 NodeCovTh 2 EdgeCovTh 1 k 51 g 15 GS 12000000 f
Illumina_500bp_2x300_R1_sampled.fastq

DBG2OLC k 17 AdaptiveTh 0.0001 KmerCovTh 2 MinOverlap 20 RemoveChimera 1
Contigs Contigs.txt f Pacbio.fasta

cat Contigs.txt Pacbio.fasta > ctg_pb.fasta

sh split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt
ctg_pb.fasta consensus_dir 2 > cns_log.txt

**Comment by yechengxi** [comment]
Hello, It looks like you did not find the correct setting even for the yeast genome. The backbone_raw file should be close in size to the contigs file. But currently I am not sure what is the mistake here.

**Comment by hermeseduardo** [comment]
Thanks! I was able to reproduce your example,N50= 543269. This was only possible selecting 50X Illumina  and 20X Pacbio. 
Why if run the pipeline with the whole dataset the N50 of the final assembly 10 times smaller?

**Comment by yechengxi** [comment]
It is likely that some thresholds are not set properly to throw away the erroneous k-mers.

**Comment by hermeseduardo** [comment]
I was able to get some better results for my dataset but using: DBG2OLC LD1 0 Contigs contig.fa k 31 KmerCovTh 10 MinOverlap 150 AdaptiveTh 0.02 f pac.fa
Is there anything to be aware off by using a larger kmer (k31)instead of k17?

**Comment by yechengxi** [comment]
k 31 is not likely to work natively with uncorrected third-gen sequencing reads as correct 31-mers are quite rare.

**Comment by fancyge** [comment]
> Hello, It looks like you did not find the correct setting even for the yeast genome. The backbone_raw file should be close in size to the contigs file. But currently I am not sure what is the mistake here.

Can I ask about the size of the files from different steps? Is the backbone_raw.fasta similar size to the final genome size as well? Why is it similar to contigs.txt file? I thought with long reads mapped to short reads assembly, backbone_raw.fasta should give a more accurate size than contigs.txt. Is this correct? Thank you.
