### ISSUE TITLE
shrinking contigs during Sparc consensus step

### ISSUE THREAD

**Issue by JohnUrban** [yechengxi/DBG2OLC#4]
Hi,

Thanks for developing these interesting tools. I found out about dbg2olc here:  http://biorxiv.org/content/early/2015/10/16/029306
And have since saw your arxiv article (https://arxiv.org/pdf/1410.2801.pdf).

It looks like DBG2OLC can be useful for me since I have both long and short read data. I have an insect genome of ~300 Mb to assemble (in case that info helps with suggestions later).

I gave it a try recently. The commands I used were;

```
SparseAssembler LD 0 k 51 g 15 NodeCovTh 2 EdgeCovTh 1 GS 300000000 f Illumina_50x.fastq

DBG2OLC k 17 AdaptiveTh 0.0001 KmerCovTh 2 MinOverlap 20 RemoveChimera 1 Contigs Contigs.txt f Pacbio_20x.fasta

cat Contigs.txt Pacbio_20x.fasta > ctg_pb.fasta #was pb_reads.fsta

mkdir consensus_dir
split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_pb.fasta ./consensus_dir 2 >cns_log.txt
```

Side note: `split_reads_by_backbone.py` gave a `Too many open files` error. So I made a fork with 2 other versions of that script (`split_reads_by_backbone_readdict.py` and `split_reads_by_backbone_openclose.py`) as well as a modified `split_and_run_sparc.sh` called `split_and_run_sparc.path.sh`. The latter script allows one to choose which version of ``` `to use and also runs assuming all scripts it calls on are in the PATH instead of the current working directory (e.g.`Sparc`instead of`./Sparc`). The fork is here: https://github.com/JohnUrban/DBG2OLC -- that stuff is in the branch called` split_reads_by_backbone_minimize_open_files``` if interested.

So back to my issue - I ran the commands above. 
The dbg2olc output contigs in `backbone_raw.fasta` give an N50 comparable to long read assemblers and have a total assembly size close to the expected genome size. When `backbone_raw.fasta` is broken up into separate fastas (backbone-0.fasta ..... backbone-N.fasta), the sequences are unchanged. However, after `split_and_run_sparc.sh` finishes the `final_assembly.fasta` has fewer contigs, a much smaller assembly size (~5-7% of original size), and much smaller contigs in general. When I look in the backbone-n.fasta files, they are also smaller than they originally started out. Ultimately, in terms of size, `backbone_raw.fasta` seems more correct than `final_assembly.fasta`. Nonetheless, it should go through the consensus step - so I need to figure out a solution whether through Sparc or other. It looks like the authors of the biorxiv article used `/split_and_run_pbdagcon.sh` that I assume was originally one of the utilities offered in DBG2OLC, but I cannot find it.

Can you provide me with any insights into why this is happening and/or any advice to prevent it? 

best,

  John Urban

**Comment by yechengxi** [comment]
My guess is that there may be a system issue.  The backbone_raw.fasta file indicates a good draft assembly has been produced. While in the consensus stage we may need to open a lot of files and distribute the sequences to each backbone. If this distribution is not finished properly (say if the files cannot be opened), the final consensus can be small.
