### ISSUE TITLE
How DBG2OLC deals heterozygosity?

### ISSUE THREAD

**Issue by uceleste** [yechengxi/DBG2OLC#40]
Dear Chengxi Ye,
First of all, thank you for this very efficient assembler. I would like to know how DBG2OLC deals with heterozygosity. I'll tell you my specific case. I have a quite heterozygotic genome of 350 Mb (haploid size) to assemble. With an OLC-based assembler I obtained an assembly of 400 Mb. I'm quite sure that these 50 Mb extra are due to the heterozygosity. With DBG2OLC, tuning the parameters and doing lots of assemblies thanks to its speed, I get a set of assemblies whose size varies from 400 Mb to the correct estimated 350 Mb. So, where is gone the heterozygosity? Has it been collapsed? Or discarded?
Thank you in advance!

**Comment by yechengxi** [comment]
It has been collapsed into one backbone.

**Comment by uceleste** [comment]
Perfect, thank you very much!
