### ISSUE TITLE
no more ulimit necessary

### ISSUE THREAD

**Issue by swarris** [yechengxi/DBG2OLC#41]
The file  DBG2OLC/utility/split_reads_by_backbone.py can be changed to this (line 118 and further):
```
                new_fp = open(options.output_dir + '/' + str(id) + '.reads.fasta', 'a')
                new_fp.write('>' + tuple[0] + '\n' + tuple[1] + '\n')
                new_fp.close()
```
This will open and close the file each time it is needed. Might create additional IO overhead, but ulimit can be left intact. Very handy when you're not root.

**Comment by javibio-git** [comment]
Hello swarris, 

This maybe a silly question:

Specifically, which part of the script needs to be changed? after the if or after the else statements?

Thanks!

**Comment by swarris** [comment]
I created a pull request with the changes.
