### ISSUE TITLE
478 Floating point exception

### ISSUE THREAD

**Issue by jazberna1** [yechengxi/DBG2OLC#43]
Hello,

I get '478 Floating point exception' when running a particular contigs fasta file plus only a partial set of DBG2OLC  output files:

ContigKmerIndex_HT_idx.txt
ContigKmerIndex_HT_content
ReadsInfoFrom_Pacbio.fasta
LongReadContigIndex_log.txt
LongReadContigIndex_Histogram.txt
selected_reads.txt
CleanedLongReads.txt
ChimeraIdx.txt    

I was wondering if this error is known to happen under certain circumstances specific to a particular dataset (the contigs file).

Thanks
Jorge

**Comment by yechengxi** [comment]
Hi Jorge,
Unfortunately I have not seem this error before so it could be particular to the dataset.
