### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by pdimens** [yechengxi/DBG2OLC#47]
Hello, I am trying to run DBG2OLC for an illumina-only assembly, and SparseAssembler seems to work correctly, outputting Contigs.txt, but I get this core dumped error when using DBG2OLC with the recommended configuration from the github page for illumina-only assembly:

```
Loading contigs.
703999571 k-mers in round 1.
668403631 k-mers in round 2.
Scoring method: 3
Match method: 1
Loading long read index
0 selected reads.
0 reads loaded.
./dbg1.sh: line 6: 28378 Floating point exception(core dumped) DBG2OLC LD 0 MinOverlap 31 Contigs Contigs.txt k 21 PathCovTh 2 KmerCovTh 1 i1 $FORWARD i2 $REVERSE RemoveChimera 1 ChimeraTh 2 ContigTh 2
```
My reads have 150x-200x coverage, and are forward+reverse. Additionally, all the software is being run in a `conda` environment exclusive to only DBG2OLC and its components. 

Do you have any insights on what might be going on here?

**Comment by yechengxi** [comment]
The command is wrong. DBG2OLC only takes reads using f, in your command you used i1 i2.

**Comment by pdimens** [comment]
@yechengxi Thanks for the clarification. There is no need to specify forward and reverse reads when calling DBG2OLC?

**Comment by pdimens** [comment]
@yechengxi after taking your advice, I have rerun the DBG2OLC, and after some time processing, a different segmentation fault/core dumped issue has emerged has emerged. Are you familiar with what may be happening here? 

```
Loading contigs.
703999571 k-mers in round 1.
668403631 k-mers in round 2.
Analyzing reads...
File1: ../../BFT_1st_R1.fastq
File2: ../../BFT_1st_R2.fastq
Long reads indexed. 
Total Kmers: 93106107399
Matching Unique Kmers: 69090508968
Compression time: 333618 secs.
Scoring method: 3
Match method: 1
Loading long read index
Loading file: ReadsInfoFrom_BFT_1st_R1.fastq
1417904 bad reads skipped.
31147991 reads loaded.
Loading file: ReadsInfoFrom_BFT_1st_R2.fastq
3056832 bad reads skipped.
62046677 reads loaded.
1917738 selected reads.
62046677 reads loaded.
Average size: 2
Loaded.
1917738 reads.
Calculating reads overlaps, round 1
Multiple alignment for error correction.
./dbg1.sh: line 6: 13497 Segmentation fault      (core dumped) DBG2OLC LD 0 MinOverlap 31 Contigs Contigs.txt k 21 PathCovTh 2 KmerCovTh 1 f $FORWARD f $REVERSE RemoveChimera 1 ChimeraTh 2 ContigTh 2
```

**Comment by yechengxi** [comment]
Please try to use one of the commands in the manual to start with.
Search for the following in the manual and you can see some examples.
Commands for Non-hybrid NGS Assembly

**Comment by pdimens** [comment]
@yechengxi that seemed to do the trick, thank you! Does there still need to be a consensus step with blasr after the DBG2OLC step, or is this the finished illumina assembly?

**Comment by yechengxi** [comment]
Sorry for the delay. This is the finished illumina assembly.

**Comment by pdimens** [comment]
I had sorted it out, but thank you for the repeated feedback!
