### ISSUE TITLE
 Segmentation fault (core dumped) when analyzing reads

### ISSUE THREAD

**Issue by jmodlis** [yechengxi/DBG2OLC#49]
Hi, I'm trying to run dbg2olc with a small amount of nanopore data and a pre-existing assembly.  It has repeatedly had a segmentation fault at the same step. If you have any insight as to what is going on, I would really appreciate it!  I did run selectLongestReads before hand but it just selected all of the reads since the coverage is so low.

Thanks,
Jen

Here is the command:
```
"$dbg2olcPATH"/./DBG2OLC k 17 AdaptiveTh 0.001 KmerCovTh 2 MinOverlap 20 MinLen 500 RemoveChimera 0 Contigs "$assembly" f "$selectedReads"
```

Here is the end of the outfile:
```
Loading contigs.
238092557 k-mers in round 1.
194244643 k-mers in round 2.
Analyzing reads...
File1: /data/processedData/dbg2olc_selectReads/nanoporeLongestReadsAllRuns.fasta

```

**Comment by zrlewis** [comment]
I am seeing a similar error, I think. Did you find a workaround? Any help would be appreciated.

```
Loading contigs.
20 k-mers in round 1.
19 k-mers in round 2.
Analyzing reads...
File1: PB_reads.fasta
Long reads indexed. 
Total Kmers: 157384323679
Matching Unique Kmers: 5487266
Compression time: 23756 secs.
Scoring method: 3
Match method: 2
Loading long read index
Loading file: ReadsInfoFrom_Physalia_concatenated_reads.fasta
516513 reads loaded.
/var/spool/slurmd/job25152457/slurm_script: line 13: 25169 Floating point exception(core dumped) DBG2OLC k 17 AdaptiveTh 0.01 KmerCovTh 2 MinOverlap 30 RemoveChimera 1 Contigs ContigGraph.txt f PB_reads.fasta
```

**Comment by jmodlis** [comment]
No, and I even had help from our IT department. I eventually gave up and tried links, redundans, and space-long reads instead.  I think it may have something to do with the fact that my assembly was created by an external program, but that was the whole point of using a scaffolding program.

Your error has been mentioned before in the issues - you may want to check that your input command is correct.

Jen

**Comment by zrlewis** [comment]
@jmodlis Thanks for the update. I'm sorry that you weren't able to figure it out. 

Good idea on checking my input. I think that I should have specified `Contigs.txt` and for some reason I put `ContigGraph.txt` as input. This might solve my issue.

**Comment by yechengxi** [comment]
The reason could be the contigs are created using an untested assembler. In that case the contigs may have unknown properties that are not suitable for DBG2OLC.
