### ISSUE TITLE
sparse assembly on longest illumina paired reads

### ISSUE THREAD

**Issue by olechnwin** [yechengxi/DBG2OLC#50]
Hi,
I am trying to use DBG-assembler to construct short but accurate contigs (step 1) using Illumina paired end reads.
I had ran step 0 to select longest reads. My short reads are coming from Illumina paired end reads. So, in the command below, I have all the paired reads files as inputs for SelectLongestReads.

My commands:
`fastq_ls=""
cd /gpfs0/home/gdlessnicklab/cxt050/Data/A673_WGS_VCFs/A673_10x_fastq/
mkdir selectedReads
for file in *.fastq; do fastq_ls+=" f "$file; done
~/opt/AssemblyUtility-master/compiled/SelectLongestReads sum 96000000000 longest 1 o selectedReads/Illumina_30x.fastq $fastq_ls
`

Then in the next step I simply input the Illumina selected reads file. with the 'f' option.
`~/opt/SparseAssembler g 10 k 51 LD 0 GS 9600000000 NodeCovTh 1 EdgeCovTh 0 f selectedReads/Illumina_30x.fastq
`

**Is this the way you are supposed to run it?**
Also, is there a way to speed up the SparseAssembler (step 1)? It's been running for almost 2 days.

Thank you in advance for your advice.

**Comment by yechengxi** [comment]
I think you are right. Just that you don't have to set longest 1 for illumina reads.
For your convenience, you may start with a smaller dataset or subsample your reads to make sure your settings are correct.

**Comment by olechnwin** [comment]
Thank you so much for your quick reply.
I thought it was recommended to set longest 1 and select the longest Illumina reads if I have enough reads?
is there a way to speed up step 1? Can I split the Illumina_30x.fastq file as recommended for pacbio file?

**Comment by yechengxi** [comment]
There is no way to speed up SparseAssembler. For human genome it is taking ~1 day.
You may try various other assemblers such as SOAPdenovo2 and platanus with care -- make sure the output contigs are accurate.

**Comment by olechnwin** [comment]
Thank you for your advice. Do you have any recommendation on how to check the output contigs?

**Comment by yechengxi** [comment]
Don't use anything other than the de bruijn graph part. This means don't use any aggressive extension techniques such as multi-kmer, pair end information or scaffolding.

**Comment by olechnwin** [comment]
Thank you. I decided to wait for SparseAssembler to finish. It took ~ 3 days for my human genome. I ran AssemblyStatistics on the generated Contigs.txt

 using the following command:

`AssemblyStatistics contigs Contigs.txt`

and this is the output in Contigs.txtStats.txt:
> Total len: 2806062839
> Longest contig: 15381 
> N10 2991
> N20 2152
> N30 1651
> N40 1282
> N50 984
> N60 726
> N70 493
> N80 290
> N90 152

what concerned me is that N50 is only 984 bp (I think this is bp) seems to be very low. 
**If I run this again using LD 1, will it improve the N50 a lot? or is there is something else I should do?**

Thank you in advance for your advice.

**Comment by olechnwin** [comment]
FYI, I re-run SparseAssembler using LD 1. N50 becomes longer 2234. However, total length is now smaller.

> Total len: 2 693 942 000
> Longest contig: 34 578
> N10 6711
> N20 4847
> N30 3722
> N40 2898
> N50 2234
> N60 1670
> N70 1170
> N80 705
> N90 272

**Comment by yechengxi** [comment]
This latest one seems good!
