### ISSUE TITLE
Segmentation fault with  large genome

### ISSUE THREAD

**Issue by dgavr** [yechengxi/DBG2OLC#53]
Hi yechengxi,

I have been trying to assemble a ~5-6 Gb (diploid) genome using DBG2OLC. I have 4.7Gb of Illumina contigs generated with Megahit (50x coverage) with an N50 of 1.7Kb. The Pacbio dataset consists in 150Gb of sequel subreads, which should be ~25-30x. I used the following command: `DBG2OLC Contigs $CTG k 17 RemoveChimera 1 KmerCovTh 3 MinOverlap 30 AdaptiveTh 0.01 f $PBR`

The assembly runs well up to generating the `backbone_raw.fasta` file step, point at which it crashes on a Segmentation fault (core dumped, see attached log  [dbg2olc4_5185358.out.txt](https://github.com/yechengxi/DBG2OLC/files/2863776/dbg2olc4_5185358.out.txt)). The assembly stats look good but the file appears incomplete. I tried to tune the parameters to match different potential coverages (KmerCovTh=2,3,6 MinOverlap=10,30,60 and AdaptiveTh=0.001,0.01,0.02), but all these attempts have resulted in a Segmentation fault. Do you have any recommendations?

Best wishes, 
dgavr

**Comment by yechengxi** [comment]
It could be due to the NGS assembly done by Megahit. There can be some inconsistency in format that leads to the error.

**Comment by yechengxi** [comment]
I have fixed some bugs in the process, could you check again to see if the problem still persists?
