### ISSUE TITLE
Empty sequence loaded. It looks like you have messed up the data.

### ISSUE THREAD

**Issue by helaersr** [yechengxi/DBG2OLC#55]
Hi,

I try to assemble a genome from Illumina short reads and MinION long reads.
I first ran SparseAssembler on Illumina reads :
`SparseAssembler LD 0 NodeCovTh 1 EdgeCovTh 0 k 31 g 15 PathCovTh 100 GS 80000000 i1 $IlluminaReadsR1 i2 $IlluminaReadsR2`

Then DBG2OLC using the Contigs.txt file generated by SparseAssembler and MinION fastq.
`DBG2OLC LD1 0 k 17 KmerCovTh 10 MinOverlap 20 AdaptiveTh 0.01 Contigs Contigs.txt f longReads.fastq`

Everything seems to going fine until DBG2OLC tries to produce the backbone_raw.fasta file :
```
Loading contigs.
36497978 k-mers in round 1.
34042305 k-mers in round 2.
Analyzing reads...
File1: longReads.fastq
Long reads indexed.
Total Kmers: 10098923862
Matching Unique Kmers: 2127935195
Compression time: 15430 secs.
Scoring method: 3
Match method: 2
Loading long read index
Loading file: ReadsInfoFrom_longReads.fastq
1926913 reads loaded.
Average size: 9
Loaded.
1926913 reads.
Calculating reads overlaps, round 1
1000000 reads aligned.
Avg alignment size: 9
total alignments: 11084129
Avg alignment size: 9
Avg sparse alignment size: 4
20453471 alignments calculated.
Round 1 takes 2799 secs.
Calculating reads overlaps, round 2
1000000 reads aligned.
Avg alignment size: 8
total alignments: 8081896
Avg alignment size: 8
Avg sparse alignment size: 3
15774478 alignments calculated.
Round 2 takes 1577 secs.
1374023 contained out of 1926913
80366 tips in the graph.
Graph simplification.
Iteration: 0
42279 branching positions.
14715 linear nodes.
Iteration: 1
18949 branching positions.
18899 linear nodes.
Iteration: 2
11995 branching positions.
20207 linear nodes.
Iteration: 3
10289 branching positions.
20375 linear nodes.
57091 edges deleted.
0 chimeric reads deleted.
2802 bad nodes removed in aggrassive cleaning.
52312 tips in the graph.
Loading contigs.
Collecting information for consensus.
1926913 reads.
Calculating reads overlaps.
1000000 reads aligned.
Avg alignment size: 13
Avg sparse alignment size: 3
total alignments: 119110145
Avg alignment size: 12
Avg sparse alignment size: 3
226226058 alignments calculated.
27238 secs.
Loading non-contained sequences.
0 loaded.
frag sum: 564254854
offset sum: 172184934
Empty sequence loaded. It looks like you have messed up the data.
Assembly finished.
```

I tried to put the Contigs.txt and longreads.fastq in the working directory of DBG2OLC, but I still get the empty sequence loaded. Any idea of what could cause the problem ?

Thanks

**Comment by yechengxi** [comment]
At the time of the development, only fasta is supported for the long reads. Please see if that solves the problem.

**Comment by yechengxi** [comment]
The problem is that you have a read that is empty. Could you go over your data set and make sure of that?

**Comment by helaersr** [comment]
I didn't find any empty sequence, but following your first comment I convert the fastq file with long reads to a fasta, and it worked ! I only got lots of "Extension warning." but all files seem to have been generated.

Thanks for your help
