### ISSUE TITLE
setting ulimit -n unlimited is impossible on Linux OS

### ISSUE THREAD

**Issue by tao-bioinfo** [yechengxi/DBG2OLC#6]
On Linux OS, setting `ulimit -n unlimited` is impossible. The default value is 1024. We could enlarge this value by edit /etc/security/limits.conf and set:

```
*   hard    nofile  65535
*   soft    nofile  65535
```

However, we could not set it to unlimited, as this would destroy the system and make user login fail

**Comment by donlantican** [comment]
I am also having the same problem.

**Comment by tao-bioinfo** [comment]
@donlantican Well, you can use https://github.com/JohnUrban/DBG2OLC/tree/split_reads_by_backbone_minimize_open_files
