### ISSUE TITLE
Linked reads + PacBio reads

### ISSUE THREAD

**Issue by francicco** [yechengxi/DBG2OLC#60]
Hi,

I'm very keen to test the DBG2OLC pipeline with my data. I have linked reads (10x Chromium at 100x) and PacBio reads (low coverage ~35x). I assembled a first draft of the genome with Supernova, can I use that assembly to give it as input to DBG2OLC skipping the step 1 of the pipeline?

Thanks
Francesco

**Comment by yechengxi** [comment]
That really depends on how the data from Supernova looks like. You have to play around to know.
