### ISSUE TITLE
Empty sequence loaded. It looks like you have messed up the data.

### ISSUE THREAD

**Issue by pgaiero** [yechengxi/DBG2OLC#63]
Hi! I got this error message when trying to use two long reads files, one from PacBio and another from MinION. Does DBG2OLC support both kinds of files?
Here's what I did:
nohup /DATOS/pgaiero/DBG2OLC_git/compiled/DBG2OLC k 17 AdaptiveTh 0.001 KmerCovTh 2 MinOverlap 20 RemoveChimera 1 Contigs /DATOS/pgaiero/Paspalum_umbrosum_denovo_Illumina/Illumina_assembly_PE_dedupe2/Contigs.txt f /DATOS/pgaiero/Paspalum_umbrosum_denovo_Illumina/Illumina_assembly_PE_dedupe2/Pumbrosum_subreads.fastq f /DATOS/pgaiero/Paspalum_umbrosum_denovo_Illumina/Illumina_assembly_PE_dedupe2/concatenated_MinION_pass.fq &

And here's the message I got:
Loading contigs.
Collecting information for consensus.
1317355 reads.
Calculating reads overlaps.
1000000 reads aligned.
Avg alignment size: 54
Avg sparse alignment size: 3
total alignments: 13815382
Avg alignment size: 54
Avg sparse alignment size: 3
13869759 alignments calculated.
1288 secs.
Loading non-contained sequences.
191590 loaded.
frag sum: 1072099954
offset sum: 347043943
Empty sequence loaded. It looks like you have messed up the data.
Assembly finished.

I made sure that all files were in the working directory so the problem is not the same as in this issue.
Would you mind pointing out what's wrong?
Thanks a million for your help!

**Comment by yechengxi** [comment]
It looks like you have a read that is empty. Please remove all reads that have Ns or are empty.
