### ISSUE TITLE
No release management?

### ISSUE THREAD

**Issue by cmeesters** [yechengxi/DBG2OLC#64]
Dear DBG2OLC developers,

I am a Computational Scientist and provide ( besides others tasks) software on our cluster. Without releases (for instance   https://en.wikipedia.org/wiki/Software_versioning#Degree_of_compatibility ) we are not able to provide a coherent install of your software. 

If you would contemplate to provide a release bundle along with fixes / updates in your master branch, that would be great - and presumably beneficial to the software.

Best regards,
Christian Meesters

**Comment by hmontenegro** [comment]
I second this suggestion. It makes easier to manage locally installed versions, and it would probably benefit the people packaging DBG2OLC externally, such as in conda.

**Comment by yechengxi** [comment]
These are good suggestions. I will consider it.
