### ISSUE TITLE
Just give you some suggestions!

### ISSUE THREAD

**Issue by yueyuanliu** [yechengxi/DBG2OLC#65]
The script 'split_and_run_sparc.sh' has some problems, for example, 'cmd="cat ${split_dir}/*.consensus.fasta > ${split_dir}/final_assembly.fasta"', 'cat: './consensus_dir/*.consensus.fasta': No such file or directory'.
Now, I used python2.7 to modify this script:
import sys,os
path="..."
for file in os.listdir(path):
        if file.endswith("reads.fasta"):
                file1=file[:-12]
                os.system('blasr %s %s.fasta --nproc 200 --bestn 1 -m 5 --minMatch 19 --out %s.mapped.m5'%(file,file1,file1))
                os.system('Sparc m %s.mapped.m5 b %s.fasta k 1 c 2 g 1 HQ_Prefix Contig boost 5 t 0.2 o %s'%(file1,file1,file1))
                #os.system('mv %s.consensus.fasta %s.fasta'%(file1,file1))
                os.system('rm %s.mapped.m5'%(file1))
                os.system('rm %s'%(file))
                os.system('cat %s*.consensus.fasta >final_assembly.fasta'%(file1))
Maybe this works better!

**Comment by yechengxi** [comment]
Good suggestion. Please feel free to contribute to this repository.
