### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by baizixiansheng** [yechengxi/DBG2OLC#66]
Hi，I have this problem when I am running. Could you give me some advice?
`$ /home/chens/Bio-soft/DBG2OLC/SparseAssebmler LD 1 k 95 g 15 NodeCovTh 2 EdgeCovTh 1 GS 2400000000 f /data/read/Illumina/Stylosanthesguianensis_D148-D01_good_1.fq.gz f /data/read/Illumina/Stylosanthesguianensis_D148-D01_good_2.fq.gz f /data/read/Illumina/Stylosanthesguianensis_D148-D02_good_1.fq.gz f /data/read/Illumina/Stylosanthesguianensis_D148-D02_good_2.fq.gz`
`chens@master-hndx:/data/assembly/DBG2OLC-ex$ /home/chens/Bio-soft/DBG2OLC/SparseAssebmler LD 1 k 95 g 15 NodeCovTh 2 EdgeCovTh 1 GS 2400000000 f /data/read/Illumina/Stylosanthesguianensis_D148-D01_good_1.fq.gz f /data/read/Illumina/Stylosanthesguianensis_D148-D01_good_2.fq.gz f /data/read/Illumina/Stylosanthesguianensis_D148-D02_good_1.fq.gz f /data/read/Illumina/Stylosanthesguianensis_D148-D02_good_2.fq.gz`
` Example command: `
`For third-gen sequencing: DBG2OLC LD1 0 Contigs contig.fa k 17 KmerCovTh 2 MinOverlap 20 AdaptiveTh 0.005 f reads_file1.fq/fa f reads_file2.fq/fa`
`For sec-gen sequencing: DBG2OLC LD1 0 Contigs contig.fa k 31 KmerCovTh 0 MinOverlap 50 PathCovTh 1 f reads_file1.fq/fa f reads_file2.fq/fa`
`Parameters:`
`MinLen: min read length for a read to be used.`
`Contigs:  contig file to be used.`
`k: k-mer size.`
`LD: load compressed reads information. You can set to 1 if you have run the algorithm for one round and just want to fine tune the following parameters.`
`PARAMETERS THAT ARE CRITICAL FOR THE PERFORMANCE:`
`If you have high coverage, set large values to these parameters.`
`KmerCovTh: k-mer matching threshold for each solid contig. (suggest 2-10)`
`MinOverlap: min matching k-mers for each two reads. (suggest 10-150)`
`AdaptiveTh: [Specific for third-gen sequencing] adaptive k-mer threshold for each solid contig. (suggest 0.001-0.02)`
`PathCovTh: [Specific for Illumina sequencing] occurence threshold for a compressed read. (suggest 1-3)`
`Author: Chengxi Ye cxy@umd.edu.`
`last update: Jun 11, 2015.`
`Scoring method: 3`
`Match method: 1`
`Loading long read index`
`Loading file: ReadsInfoFrom_Stylosanthesguianensis_D148-D01_good_1.fq.gz`
`0 bad reads skipped.`
`0 reads loaded.`
`Loading file: ReadsInfoFrom_Stylosanthesguianensis_D148-D01_good_2.fq.gz`
`0 bad reads skipped.`
`0 reads loaded.`
`Loading file: ReadsInfoFrom_Stylosanthesguianensis_D148-D02_good_1.fq.gz`
`0 bad reads skipped.`
`0 reads loaded.`
`Loading file: ReadsInfoFrom_Stylosanthesguianensis_D148-D02_good_2.fq.gz`
`0 bad reads skipped.`
`0 reads loaded.`
`0 selected reads.`
`0 reads loaded.
`

**Comment by yechengxi** [comment]
You need to extract the gz files into fasta/fastq.
