### ISSUE TITLE
merging of final backbone contigs to illumina assembly

### ISSUE THREAD

**Issue by pradeepphule** [yechengxi/DBG2OLC#67]
i followed all steps given in manual, now i have consensus of backbone fasta and illumina contigs from spaseassembler.
how to merge extended backbone contigs from consensus step to assembled illumina contigs from sparseassembler to make final assembly?

**Comment by yechengxi** [comment]
You want to follow the consensus step. Concatenate the illumina contigs and the long reads together into one file, as in the documentation.
