### ISSUE TITLE
Extension warning

### ISSUE THREAD

**Issue by HenrivdGeest** [yechengxi/DBG2OLC#7]
Hi,
Often when I perform a parameter sweep of kmercovth, minoverlap and adaptiveTh I get some "Extension warning" messages and the end of the assembly process.
For some parameters, I get one or two, some times more than 10 and sometimes not at all. (with the same dataset)

How should we interpret these messages? And how bad are these messages? Are they for sure represent misassemblies , like 2 falsely joined contigs?

I am working or plant genomes, currently a few hundreds of  magabases in size with 10-20x pacbio coverage.

For example:
``....
total alignments: 4526698
Avg alignment size: 9
Avg sparse alignment size: 3
4959403 alignments calculated.
67 secs.
Loading non-contained sequences.
180272 loaded.
frag sum: 823679464
offset sum: 333620515
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Extension warning.
Assembly finished.

```
```

**Comment by yechengxi** [comment]
The extension warnings are usually caused by some chimeric reads. In essence it tells that there may be some structural errors when DBG2OLC joins the raw pacbio reads. You can simply disregard them.
