### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by Aphrix** [yechengxi/DBG2OLC#71]
Hello, 
I am encountering a segmentation fault. Apparently, everything stopped during the multiple alignment for error correction. Thanks for your help.

**error** 
DBG2OLC[45500]: segfault at 28 ip 000055b60cb32140 sp 00007ffc827b5f70 error 4 in DBG2OLC[55b60cb09000+4f000]
**command** 
DBG2OLC k 17 AdaptiveTH 0.01 KmerCovTh 3 MinOverlap 20 Contigs short-reads-contigs.fa f long-reads.fa RemoveChimera 1
**log**
Loading contigs.
383754216 k-mers in round 1.
344563592 k-mers in round 2.
Analyzing reads...
File1: /data/Astacus/long-reads-CCS-1000.fa
Long reads indexed. 
Total Kmers: 11659391465
Matching Unique Kmers: 1378134164
Compression time: 22933 secs.
Scoring method: 3
Match method: 1
Loading long read index
Loading file: ReadsInfoFrom_long-reads-CCS-1000.fa
1420614 bad reads skipped.
1557966 reads loaded.
130191 selected reads.
1557966 reads loaded.
Average size: 4
Loaded.
130191 reads.
Calculating reads overlaps, round 1
Multiple alignment for error correction.

**Comment by yechengxi** [comment]
I cannot tell what the error could be from these outputs.
