### ISSUE TITLE
Smaller consensus.  

### ISSUE THREAD

**Issue by Yuma248** [yechengxi/DBG2OLC#72]
Dear: 

I have a genome ~0.7Gb  size, and I have short illumina reads 100x and long read PacBio 100x. When I run the first part of DBG2OLC I got a backbone.fasta files with 1,730 contigs, the longest is  7,309,642 and the N50 is 1,247,446. However, after running the sparc script I got a final_consensus.fasta  with also 1,730 contigs, but the longest is  7,160,684 and the N50 is 1,226,913 and basically most of the new scaffolds are 2% smaller. Is this normal? Or I am doing something wrong?

Thanks

**Comment by yechengxi** [comment]
This is normal.
