### ISSUE TITLE
How to use paired-end reads (R1 and R2) in SparseAssembler

### ISSUE THREAD

**Issue by khaled8523** [yechengxi/DBG2OLC#73]
Hello 
I want to assemble my short reads with SparseAssembler but I didn't get how I can fed in both R1 and R2 at same time in this program. 
Here is my code and result of assembly is terrible.
#cod
SparseAssembler LD 1 k 51 g 15 NodeCovTh 1 EdgeCovTh 0 GS 1400000000 f i1 pure_nova.R1.fq i2 pure_nova.R2.fq
 

#result
sum = 2212747077, n = 26724939, ave = 82.80, largest = 25297
N50 = 81, n = 7055056
N60 = 66, n = 10078196
N70 = 53, n = 13720507
N80 = 51, n = 18047500
N90 = 51, n = 22386220
N100 = 51, n = 26724939

**Comment by yechengxi** [comment]
For DBG2OLC we just want to use the information from single end reads to avoid introducing errors. The result is indeed poor. Is it a difficult genome?

**Comment by khaled8523** [comment]
It means SparseAssembler is not able to use paired-end reads at all? No it is not a difficult genome.

**Comment by yechengxi** [comment]
SparseAssembler cannot handle paired reads well. This is more like an error. If you run the assembly for the first time, please set LD 0, and use f to feed the reads files.
