### ISSUE TITLE
Error! Maximal alignment length reached. max_len: 250

### ISSUE THREAD

**Issue by ZhangZhenmiao** [yechengxi/DBG2OLC#76]
Hello, I am running the DBG2OLC program and it printed "Error! Maximal alignment length reached. max_len: 250" many times. Were there any problems in my running? If yes, how could I avoid the error? Thanks!

**Comment by yechengxi** [comment]
No-- in fact you are having a high quality assembly which is too long for the default parameters to deal with.

**Comment by ZhangZhenmiao** [comment]
Thank you for quick reply!
