### ISSUE TITLE
Is it ContigTh or ContigCovTh?

### ISSUE THREAD

**Issue by shelkmike** [yechengxi/DBG2OLC#78]
The manual of DBG2OLC mentions a parameter ContigTh: "ContigTh: default: 1, set to 2 if coverage is ~100x."
However, in the source code of DBG2OLC there is no such parameter, but there is a parameter ContigCovTh.
Is this a typo in the manual?
Also, thank you for a good genome assembler. It helped me to assemble several genomes which had low long read coverage.

**Comment by yechengxi** [comment]
Thank you for pointing it out. It is a typo.
