### ISSUE TITLE
KeyError: 'Backbone_9625'

### ISSUE THREAD

**Issue by hermeseduardo** [yechengxi/DBG2OLC#8]
Hi, I am getting the following message: 

sh ./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_pb.fasta ./consensus_dir 2 >cns_log.txt
Traceback (most recent call last):
  File "./split_reads_by_backbone.py", line 131, in <module>
    main()
  File "./split_reads_by_backbone.py", line 114, in main
    id = backbone_to_id[backbone]
KeyError: 'Backbone_9625'

any help will be appreciated,

thanks

**Comment by yue9404** [comment]
i get same error, did you figure it out?
