### ISSUE TITLE
SelectLongestReads: 'std::length_error'

### ISSUE THREAD

**Issue by CeciliaDeng** [yechengxi/DBG2OLC#9]
Hi 

I tried to run
`DBG2OLC/compiled/SelectLongestReads sum 18000000000 longest 0 o Illumina_PElib_30x.fasta f PElib_1.fastq.gz f PElib_2.fastq.gz`

File Illumina_PElib_30x.fasta (with small file size) was created, but the command exit with 

> terminate called after throwing an instance of 'std::length_error'
>   what():  basic_string::resize
> /home/hrachd/.lsbatch/1476836888.83252: line 8: 28640 Aborted                 (core dumped)

The FASTQC reports for both PElib_[1/2].fastq.gz files confirmed the read length is 101 bases for all reads.

Any idea how to fix the problem? Thank you very much.

**Comment by yechengxi** [comment]
you need to unzip first.
